services:
  db-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${TEST_POSTGRES_DB:-todos_test}
    ports:
      - '${TEST_DB_PORT:-5433}:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${TEST_POSTGRES_USER:-postgres} -d ${TEST_POSTGRES_DB:-todos_test}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
